name: spotify
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/vectors/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/SatoShi-Black.ttf
          weight: 900
        - asset: assets/fonts/SatoShi-Bold.ttf
          weight: 600
        - asset: assets/fonts/SatoShi-Regular.ttf
          weight: 500
        - asset: assets/fonts/SatoShi-Medium.ttf
          weight: 400
        - asset: assets/fonts/SatoShi-Light.ttf
          weight: 300
